
# Kommando für einen docker container ohne compose:
# docker run --rm -it -p 1313:1313 -v "$PWD":/src klakegg/hugo:0.54.0-ext-alpine server --bind=0.0.0.0

services:
  hugoserver:
    image: klakegg/hugo:0.54.0-ext-alpine
    command: server --bind=0.0.0.0
    ports:
      - "1313:1313"
    volumes:
      - $PWD:/src
    
# Starten mit docker compose up
# Beenden mit Strg + c
# Entfernen mit docker compose down